# -*- coding: utf-8 -*-
"""URLPNGhozon .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYUzClgZkAxjvL9AU2dx6QLM_pIRfFJY
"""

pip install selenium pillow

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from PIL import Image
import time

# WebDriverの設定
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

# ウェブページを開く
driver.get('https://　')

# ページが完全にロードされるのを待つ
time.sleep(5)

# スクリーンショットを取る
driver.save_screenshot('webpage_screenshot.png')

# 画像ファイルを開く
image = Image.open('webpage_screenshot.png')

# PNGとして保存
image.save('Desktop/webpage_image.png', 'PNG')

# WebDriverを閉じる
driver.quit()