# -*- coding: utf-8 -*-
"""ドットの数のカウント2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFKGhJgwTONGovXrP2pO11Y4YHiS7s3G
"""

pip install opencv-python-headless numpy

import requests
from bs4 import BeautifulSoup
import cv2
import numpy as np



def count_dots(image):
# 画像の読み込み
    image = cv2.imread(image_path)
    # 画像のサイズ取得
    height, width, _ = image.shape

    # 100x100ピクセルごとの分割
    grid_size = 100

    for y in range(0, height, grid_size):
        for x in range(0, width, grid_size):
            # グリッド内の領域を取得
            grid = image[y:y+grid_size, x:x+grid_size]

            # 青色と赤色のマスクを作成
            lower_blue = np.array([100, 0, 0])
            upper_blue = np.array([255, 150, 150])
            blue_mask = cv2.inRange(grid, lower_blue, upper_blue)

            lower_red = np.array([0, 0, 100])
            upper_red = np.array([150, 150, 255])
            red_mask = cv2.inRange(grid, lower_red, upper_red)

            # ドットの数をカウント
            blue_dots = cv2.countNonZero(blue_mask)
            red_dots = cv2.countNonZero(red_mask)

            # 結果を表示
            print(f"Grid ({x}, {y}) - Blue dots: {blue_dots}, Red dots: {red_dots}")

if __name__ == "__main__":
    image_path = r"C:\Users\gakut\OneDrive\デスクトップ\スクリーンショット 2024-05-19 140640.png"  # 画像のパスを指定
    count_dots(image_path)